# Importing the necessary library

In [58]:
import pandas as pd
import sklearn

### Load the dataset

In [59]:
movies_df = pd.read_csv("Hydra-Movie-Scrape.csv")

In [60]:
# visulaize the dataset
movies_df.head()

,Title,Year,Summary,Short Summary,Genres,IMDB ID,Runtime,YouTube Trailer,Rating,Movie Poster,Director,Writers,Cast
0,Patton Oswalt: Annihilation,2017,"Patton Oswald, despite a personal tragedy, pro...","Patton Oswalt, despite a personal tragedy, pro...",Uncategorized,tt7026230,66,4hZi5QaMBFc,7.4,https://hydramovies.com/wp-content/uploads/201...,Bobcat Goldthwait,Patton Oswalt,Patton Oswalt
1,New York Doll,2005,A recovering alcoholic and recently converted ...,A recovering alcoholic and recently converted ...,Documentary|Music,tt0436629,75,jwD04NsnLLg,7.9,https://hydramovies.com/wp-content/uploads/201...,Greg Whiteley,Arthur Kane,Sylvain Sylvain
2,Mickey's Magical Christmas: Snowed in at the H...,2001,After everyone is snowed in at the House of Mo...,Mickey and all his friends hold their own Chri...,Adventure|Animation|Comedy|Family|Fantasy,tt0300195,65,uCKwHHftrU4,6.8,https://hydramovies.com/wp-content/uploads/201...,Tony Craig,Thomas Hart,Carlos Alazraqui|Wayne Allwine
3,Mickey's House of Villains,2001,The villains from the popular animated Disney ...,The villains from the popular animated Disney ...,Animation|Comedy|Family|Fantasy|Horror,tt0329374,0,JA03ciYt-Ek,6.6,https://hydramovies.com/wp-content/uploads/201...,Jamie Mitchell,Thomas Hart,Tony Anselmo|Wayne Allwine
4,And Then I Go,2017,"In the cruel world of junior high, Edwin suffe...","In the cruel world of junior high, Edwin suffe...",Drama,tt2018111,99,8CdIiD6-iF0,7.6,https://hydramovies.com/wp-content/uploads/201...,Vincent Grashaw,Brett Haley,Arman Darbo|Sawyer Barth

In [66]:
# removing column that are not very useful
movies_df = movies_df.drop(['IMDB ID', 'Runtime','YouTube Trailer','Summary'], axis=1)

In [71]:
# checking for the current state of the dataset
movies_df.head()

,Title,Year,Short Summary,Genres,Rating,Movie Poster,Director,Writers,Cast
0,Patton Oswalt: Annihilation,2017,"Patton Oswalt, despite a personal tragedy, pro...",Uncategorized,7.4,https://hydramovies.com/wp-content/uploads/201...,Bobcat Goldthwait,Patton Oswalt,Patton Oswalt
1,New York Doll,2005,A recovering alcoholic and recently converted ...,Documentary|Music,7.9,https://hydramovies.com/wp-content/uploads/201...,Greg Whiteley,Arthur Kane,Sylvain Sylvain
2,Mickey's Magical Christmas: Snowed in at the H...,2001,Mickey and all his friends hold their own Chri...,Adventure|Animation|Comedy|Family|Fantasy,6.8,https://hydramovies.com/wp-content/uploads/201...,Tony Craig,Thomas Hart,Carlos Alazraqui|Wayne Allwine
3,Mickey's House of Villains,2001,The villains from the popular animated Disney ...,Animation|Comedy|Family|Fantasy|Horror,6.6,https://hydramovies.com/wp-content/uploads/201...,Jamie Mitchell,Thomas Hart,Tony Anselmo|Wayne Allwine
4,And Then I Go,2017,"In the cruel world of junior high, Edwin suffe...",Drama,7.6,https://hydramovies.com/wp-content/uploads/201...,Vincent Grashaw,Brett Haley,Arman Darbo|Sawyer Barth

In [67]:
movies_df.describe()

              Year       Rating
count  3940.000000  3940.000000
mean   2012.132741     6.555685
std       4.821189     0.892572
min    2000.000000     1.700000
25%    2009.000000     6.100000
50%    2013.000000     6.600000
75%    2016.000000     7.100000
max    2018.000000     9.500000

In [68]:
movies_df.shape[1]

9

In [69]:
#checking for null values
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3940 entries, 0 to 3939
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Title          3940 non-null   object
 1   Year           3940 non-null   int64
 2   Short Summary  3939 non-null   object
 3   Genres         3940 non-null   object
 4   Rating         3940 non-null   float64
 5   Movie Poster   3940 non-null   object
 6   Director       3940 non-null   object
 7   Writers        3922 non-null   object
 8   Cast           3916 non-null   object
dtypes: float64(1), int64(1), object(7)
memory usage: 277.2+ KB

In [70]:
# creating a very simple user interface
print("Welcome to Movie Hub")
print("Please enter the name of the movie")
name = input("Enter your movie name: ")

# Filter DataFrame based on user input
matching_movies = movies_df[movies_df["Title"].str.contains(name, case=False, na=False)]

if not matching_movies.empty:
    print("Matching Movies:")
    display(matching_movies)
else:
    print("Movie not found. Enter something else")
    year = input("Enter the year the movie was released in: ")
    
    # Convert year to integer
    try:
        year = int(year)
        matching_movies_by_year = movies_df[movies_df["Year"] == year]
        
        if not matching_movies_by_year.empty:
            print("Movies released in", year)
            display(matching_movies_by_year)
            #print(tabulate(matching_movies, headers='keys', tablefmt='grid'))
        else:
            print("No movies found for the entered year. See you again!")
            genres = input("Enter the genres of the movie")
            try:
                matching_movie_by_genres = movies_df[movies_df["Genres"].str.contains(genres, case=False, na=False)]
                if not matching_movie_by_genres.empty:
                    print("movies by genres")
                    display(matching_movie_by_genres)
                else:
                    print("NO movie with that generes")
            except ValueError:
                print("Invalid format. Please enter a genres.")

    except valueError:
        print("Thank for visiting")

Welcome to Movie Hub
Please enter the name of the movie

Enter your movie name:  inception

Matching Movies:

,Title,Year,Short Summary,Genres,Rating,Movie Poster,Director,Writers,Cast
2149,Inception,2010,A thief who steals corporate secrets through t...,Action|Adventure|Crime|Mystery|Sci-Fi,8.8,https://hydramovies.com/wp-content/uploads/201...,Christopher Nolan,Christopher Nolan,Ellen Page|Joseph Gordon-Levitt|Leonardo DiCaprio